spring.application.name=FAMS
server.port=9090
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akinrindeakinkunmi2006@gmail.com
spring.mail.password=meqxuztxiiqfmqvz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true